//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        public int Bus_id { get; set; }
        public Nullable<int> Bus_number { get; set; }
        public string Bus_name { get; set; }
        public string Source_station { get; set; }
        public string Destination { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime enddate { get; set; }
        public int Duration { get; set; }
        public int Available_number_of_seats { get; set; }
    }
}
