//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancel_Ticket
    {
        public int Booking_Id { get; set; }
        public int Transaction_Id { get; set; }
        public double Refunded_Amount { get; set; }
        public int Cancellation_Id { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
