//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]

    public partial class OTP
    {
        [DataMember]
        public int Id { get; set; }
        public Nullable<int> OTP1 { get; set; }
        public Nullable<int> Registration_Id { get; set; }
    
        public virtual Registration Registration { get; set; }
    }
}
