//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BusEnquiry.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]

    public partial class Bus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bus()
        {
            this.Bookings = new HashSet<Booking>();
        }
        [DataMember]
        public int Bus_id { get; set; }
        [DataMember]
        public Nullable<int> Bus_number { get; set; }
        [DataMember]
        public string Bus_name { get; set; }
        [DataMember]
        public string Source_station { get; set; }
        [DataMember]
        public string Destination { get; set; }
        [DataMember]
        public System.DateTime startdate { get; set; }
        [DataMember]

        public System.DateTime enddate { get; set; }
        [DataMember]

        public int Duration { get; set; }
        [DataMember]
        public int Available_number_of_seats { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
